# Fly.io Template Configuration for Debrief Extension PR Previews
# This is a template file that will be dynamically modified during CI/CD
# The app name will be replaced with: pr-<PR_NUMBER>-futuredebrief
# The deployment will be accessible at: https://pr-<PR_NUMBER>-futuredebrief.fly.dev

app = "PR_APP_NAME_PLACEHOLDER"
primary_region = "dfw"

[build]
  # Use the existing Dockerfile for code-server with Debrief extension

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "60s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  # Optimized resource allocation for code-server workloads
  # Cost-effective while ensuring good performance
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  # Environment variables for code-server operation
  PASSWORD = ""
  SUDO_PASSWORD = ""
  # Disable telemetry for privacy and performance
  DISABLE_TELEMETRY = "true"
  # Set proper timezone
  TZ = "UTC"
  # Add PR number for identification
  PR_NUMBER = "PR_NUMBER_PLACEHOLDER"

# No persistent storage - stateless operation as required
# All data is ephemeral and reset with each deployment

[processes]
  app = "code-server --bind-addr 0.0.0.0:8080 --auth none --disable-telemetry /home/coder/workspace"