name: Build Extension

on:
  push:
    branches: [ main, test-dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Compile TypeScript
      run: npm run compile
    
    - name: Package extension
      run: npx @vscode/vsce package --out extension.vsix
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-vsix
        path: "extension.vsix"
        retention-days: 30
    
    - name: Post codespace link comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const repoUrl = context.repo.owner + '/' + context.repo.repo;
          const branch = context.payload.pull_request.head.ref;
          const codespaceUrl = `https://codespaces.new/${repoUrl}?quickstart=1&ref=${branch}`;
          
          // Delete existing extension build comments
          const comments = await github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          
          const botComments = comments.data.filter(comment => 
            comment.user.login === 'github-actions[bot]' && 
            comment.body.includes('Extension built successfully!')
          );
          
          for (const comment of botComments) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id
            });
            console.log(`Deleted comment ${comment.id}`);
          }
          
          // Post new comment
          const comment = `🚀 **Extension built successfully!**
          
          The VS Code extension has been packaged and is ready for testing.
          
          **Try it in a codespace:**
          [![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](${codespaceUrl})
          
          The extension will be automatically installed when the codespace starts up.`;
          
          const newComment = await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
          
          console.log(`Posted new comment ${newComment.data.id}`);