name: CI - Main Branch Build

on:
  push:
    branches: [main]
  # Remove pull_request trigger since pr-preview.yml handles PR builds

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Compile TypeScript
      run: npm run compile
    
    - name: Install vsce
      run: |
        # Install vsce with fallback to local installation
        npm install -g @vscode/vsce || npm install @vscode/vsce
    
    - name: Package extension (dry run)
      run: |
        # Test packaging without creating actual .vsix file
        if which vsce > /dev/null 2>&1; then
          vsce package --out test-extension.vsix
        else
          npx vsce package --out test-extension.vsix
        fi
        ls -la *.vsix
        rm -f *.vsix
    
    - name: Verify Docker build context
      run: |
        # Verify Dockerfile exists and is valid
        docker build --dry-run -f Dockerfile . || echo "Docker build test failed"
        
        # Check important files are present
        echo "Checking project structure..."
        test -f package.json && echo "✅ package.json exists"
        test -f tsconfig.json && echo "✅ tsconfig.json exists"
        test -f Dockerfile && echo "✅ Dockerfile exists"
        test -f fly-template.toml && echo "✅ fly-template.toml exists"
        test -d workspace && echo "✅ workspace directory exists"
        test -d out && echo "✅ out directory exists (build successful)"