name: Enable Codespace Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  setup-codespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run compile

      - name: Add PR comment with Codespace link
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            const head_ref = context.payload.pull_request.head.ref;
            
            const codespaceUrl = `https://codespaces.new/${owner}/${repo}/tree/${head_ref}`;
            
            const comment = `## 🚀 Codespace Preview Available
            
            You can preview this extension in a GitHub Codespace:
            
            [![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](${codespaceUrl})
            
            The extension will be ready for testing once the Codespace starts up.
            
            ### Testing the Extension:
            1. Press \`F5\` to launch the Extension Development Host
            2. Test the "Hello World" command via Command Palette (\`Ctrl+Shift+P\`)
            3. Check the activation notification
            4. View the custom panel in the Explorer sidebar`;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pull_number,
              body: comment
            });